[project]
name = "context"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["context"]

[tool.setuptools.package-data]
"*" = ["*.md"]
